In [1]:
import zipfile

In [3]:
with zipfile.ZipFile('/content/healthcare_dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/healthcare_data')

In [4]:
import os
os.listdir('/content/healthcare_data')

['Final_Augmented_dataset_Diseases_and_Symptoms.csv']

In [6]:
import pandas as pd

df = pd.read_csv('/content/healthcare_data/Final_Augmented_dataset_Diseases_and_Symptoms.csv')
df.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

Warning: Total number of columns (378) exceeds max_columns (20) limiting to first (20) columns.

In [7]:
df.shape

(246945, 378)

In [8]:
df['diseases'].unique()

array(['panic disorder', 'vocal cord polyp', 'turner syndrome',
       'cryptorchidism', 'poisoning due to ethylene glycol',
       'atrophic vaginitis', 'fracture of the hand',
       'cellulitis or abscess of mouth', 'eye alignment disorder',
       'headache after lumbar puncture', 'pyloric stenosis',
       'salivary gland disorder', 'osteochondrosis', 'injury to the knee',
       'metabolic disorder', 'vaginitis', 'sick sinus syndrome',
       'tinnitus of unknown cause', 'glaucoma', 'eating disorder',
       'transient ischemic attack', 'pyelonephritis',
       'rotator cuff injury', 'chronic pain disorder',
       'problem during pregnancy', 'liver cancer', 'atelectasis',
       'injury to the hand', 'choledocholithiasis', 'injury to the hip',
       'cirrhosis', 'thoracic aortic aneurysm', 'subdural hemorrhage',
       'diabetic retinopathy', 'fibromyalgia', 'ischemia of the bowel',
       'fetal alcohol syndrome', 'peritonitis', 'injury to the abdomen',
       'acute pancreatitis', 'thrombophlebitis', 'asthma',
       'foreign body in the vagina', 'restless leg syndrome', 'emphysema',
       'cysticercosis', 'induced abortion', 'teething syndrome',
       'infectious gastroenteritis', 'acute sinusitis',
       'substance-related mental disorder', 'postpartum depression',
       'coronary atherosclerosis', 'spondylitis', 'pituitary adenoma',
       'uterine fibroids', 'idiopathic nonmenstrual bleeding',
       'chalazion', 'ovarian torsion',
       'retinopathy due to high blood pressure',
       'vaginal yeast infection', 'mastoiditis', 'lung contusion',
       'hypertrophic obstructive cardiomyopathy (hocm)',
       'ingrown toe nail', 'pulmonary eosinophilia', 'corneal disorder',
       'foreign body in the gastrointestinal tract', 'endophthalmitis',
       'intestinal malabsorption', 'viral warts', 'hyperhidrosis',
       'stroke', 'pilonidal cyst', 'crushing injury',
       'normal pressure hydrocephalus', 'alopecia',
       'hashimoto thyroiditis', 'flat feet',
       'nonalcoholic liver disease (nash)', 'hemarthrosis',
       'pelvic organ prolapse', 'fracture of the arm',
       'coagulation (bleeding) disorder', 'intracranial hemorrhage',
       'hyperkalemia', 'cornea infection', 'abscess of the lung',
       'dengue fever', 'chronic sinusitis', 'cholesteatoma', 'volvulus',
       'injury to the finger', 'poisoning due to analgesics',
       'atrial fibrillation', 'pinworm infection', 'urethral valves',
       'open wound of the neck', 'achalasia', 'conductive hearing loss',
       'abdominal hernia', 'cerebral palsy', 'marijuana abuse',
       'cryptococcosis', 'obesity', 'indigestion', 'bursitis',
       'esophageal cancer', 'pulmonary congestion',
       'juvenile rheumatoid arthritis', 'actinic keratosis',
       'acute otitis media', 'astigmatism', 'tuberous sclerosis',
       'empyema', 'presbyacusis', 'neonatal jaundice',
       'chronic obstructive pulmonary disease (copd)',
       'dislocation of the elbow', 'spondylosis', 'herpangina',
       'injury to the shoulder', 'poisoning due to antidepressants',
       'infection of open wound', 'deep vein thrombosis (dvt)',
       'protein deficiency', 'myoclonus', 'bone spur of the calcaneous',
       'von willebrand disease', 'open wound of the back', 'heart block',
       'colonic polyp', 'magnesium deficiency',
       'female infertility of unknown cause', 'pericarditis',
       'attention deficit hyperactivity disorder (adhd)',
       'pulmonic valve disease', 'tietze syndrome', 'cranial nerve palsy',
       'injury to the arm', 'conversion disorder',
       'complex regional pain syndrome', 'otosclerosis',
       'injury to the trunk', 'hypothyroidism', 'primary insomnia',
       'lice', 'vitamin b12 deficiency', 'diabetes', 'vulvodynia',
       'endometriosis', 'vasculitis', 'concussion', 'oral leukoplakia',
       'chronic kidney disease', 'bladder disorder', 'chorioretinitis',
       'priapism', 'myositis', 'mononucleosis', 'neuralgia',
       'polycystic kidney disease', 'bipolar disorder', 'amyloidosis',
       'chronic inflammatory demyelinating polyneuropathy (cidp)',
       'gastroesophageal reflux disease (gerd)', 'vitreous hemorrhage',
       'poisoning due to antimicrobial drugs', 'open wound of the mouth',
       'scleroderma', 'myasthenia gravis', 'hypoglycemia',
       'idiopathic absence of menstruation', 'dislocation of the ankle',
       'carbon monoxide poisoning', 'panic attack', 'plantar fasciitis',
       'hyperopia', 'poisoning due to sedatives', 'pemphigus',
       'peyronie disease', 'hiatal hernia',
       'extrapyramidal effect of drugs', 'meniere disease',
       'anal fissure', 'allergy', 'chronic otitis media',
       'fracture of the finger', 'hirschsprung disease',
       'polymyalgia rheumatica', 'lymphedema', 'bladder cancer',
       'acute bronchospasm', 'acute glaucoma', 'open wound of the chest',
       'dislocation of the patella', 'sciatica', 'hypercalcemia',
       'stress incontinence', 'varicose veins', 'benign kidney cyst',
       'hydrocele of the testicle', 'degenerative disc disease',
       'hirsutism', 'dislocation of the foot', 'hydronephrosis',
       'diverticulosis', 'pain after an operation', 'huntington disease',
       'lymphoma', 'dermatitis due to sun exposure',
       'anemia due to chronic kidney disease', 'injury to internal organ',
       'scleritis', 'pterygium', 'fungal infection of the skin',
       'insulin overdose',
       'syndrome of inappropriate secretion of adh (siadh)',
       'foreign body in the ear', 'premenstrual tension syndrome',
       'orbital cellulitis', 'injury to the leg',
       'hepatic encephalopathy', 'bone cancer', 'syringomyelia',
       'pulmonary fibrosis', 'mitral valve disease', 'parkinson disease',
       'gout', 'otitis media', 'drug abuse (opioids)',
       'myelodysplastic syndrome', 'fracture of the shoulder',
       'acute kidney injury', 'threatened pregnancy',
       'intracranial abscess', 'gum disease',
       'open wound from surgical incision', 'gastrointestinal hemorrhage',
       'seborrheic dermatitis', 'drug abuse (methamphetamine)',
       'torticollis', 'poisoning due to antihypertensives',
       'tension headache', 'alcohol intoxication', 'scurvy', 'narcolepsy',
       'food allergy', 'labyrinthitis', 'anxiety',
       'impulse control disorder', 'stenosis of the tear duct',
       'abscess of nose', 'omphalitis', 'leukemia', 'bell palsy',
       'conjunctivitis due to allergy', 'drug reaction', 'adrenal cancer',
       'myopia', 'osteoarthritis', 'thyroid disease', 'pharyngitis',
       'chronic rheumatic fever', 'hypocalcemia', 'macular degeneration',
       'pneumonia', 'cold sore',
       'premature ventricular contractions (pvcs)', 'testicular cancer',
       'hydrocephalus', 'breast cancer', 'anemia due to malignancy',
       'esophageal varices', 'endometrial cancer', 'cystic fibrosis',
       'intertrigo (skin condition)', 'parathyroid adenoma',
       'glucocorticoid deficiency', 'temporomandibular joint disorder',
       'wilson disease', 'vesicoureteral reflux', 'vitamin a deficiency',
       'gonorrhea', 'fracture of the rib', 'ependymoma',
       'hepatitis due to a toxin', 'vaginal cyst',
       'open wound of the shoulder', 'ectopic pregnancy',
       'chronic knee pain', 'pinguecula', 'hypergammaglobulinemia',
       'alcohol abuse', 'carpal tunnel syndrome', 'pituitary disorder',
       'kidney stone', 'autism', 'cat scratch disease',
       'chronic glaucoma', 'retinal detachment', 'aplastic anemia',
       'overflow incontinence', 'hemolytic anemia',
       'lateral epicondylitis (tennis elbow)', 'open wound of the eye',
       'syphilis', 'diabetic kidney disease', 'nose disorder',
       'drug withdrawal', 'dental caries', 'hypercholesterolemia',
       'fracture of the patella', 'kidney failure',
       'fracture of the neck', 'muscle spasm', 'hemophilia',
       'hyperosmotic hyperketotic state', 'peritonsillar abscess',
       'gastroparesis', 'itching of unknown cause', 'polycythemia vera',
       'thrombocytopenia', 'head and neck cancer',
       'pseudohypoparathyroidism', 'goiter', 'urge incontinence',
       'edward syndrome', 'open wound of the arm', 'muscular dystrophy',
       'mittelschmerz', 'corneal abrasion', 'anemia of chronic disease',
       'dysthymic disorder', 'scarlet fever',
       'hypertensive heart disease', 'drug abuse (barbiturates)',
       'polycystic ovarian syndrome (pcos)', 'encephalitis',
       'cyst of the eyelid', 'balanitis', 'foreign body in the throat',
       'drug abuse (cocaine)', 'optic neuritis', 'alcohol withdrawal',
       'premature atrial contractions (pacs)', 'hemiplegia', 'hammer toe',
       'open wound of the cheek', 'joint effusion',
       'open wound of the knee', 'meningioma', 'brain cancer',
       'placental abruption', 'seasonal allergies (hay fever)',
       'lung cancer', 'primary kidney disease', 'uterine cancer',
       'dry eye of unknown cause', 'fibrocystic breast disease',
       'fungal infection of the hair', 'tooth abscess',
       'envenomation from spider or animal bite', 'vacterl syndrome',
       'vertebrobasilar insufficiency', 'rectal disorder',
       'atonic bladder', 'benign paroxysmal positional vertical (bppv)',
       'blepharospasm', 'sarcoidosis', 'metastatic cancer',
       'trigger finger (finger disorder)', 'stye', 'hemochromatosis',
       'osteochondroma', 'cushing syndrome', 'typhoid fever',
       'vitreous degeneration', 'atrophic skin condition',
       'aspergillosis', 'uterine atony', 'trichinosis', 'whooping cough',
       'open wound of the lip', 'subacute thyroiditis',
       'oral mucosal lesion', 'open wound due to trauma',
       'intracerebral hemorrhage', 'alzheimer disease', 'vaginismus',
       'systemic lupus erythematosis (sle)', 'premature ovarian failure',
       'thoracic outlet syndrome', 'ganglion cyst',
       'dislocation of the knee', 'crohn disease',
       'postoperative infection', 'folate deficiency', 'fluid overload',
       'atrial flutter', 'skin disorder', 'floaters', 'tooth disorder',
       'heart attack', 'open wound of the abdomen', 'fracture of the leg',
       'oral thrush (yeast infection)', 'pityriasis rosea',
       'allergy to animals', 'orthostatic hypotension',
       'obstructive sleep apnea (osa)', 'hypokalemia', 'psoriasis',
       'dislocation of the shoulder', 'intussusception', 'cervicitis',
       'abscess of the pharynx', 'primary thrombocythemia',
       'arthritis of the hip', 'decubitus ulcer', 'hypernatremia',
       'sensorineural hearing loss', 'chronic ulcer', 'osteoporosis',
       'ileus', 'sickle cell crisis', 'urethritis', 'prostatitis',
       "otitis externa (swimmer's ear)",
       'poisoning due to anticonvulsants', 'testicular torsion',
       'tricuspid valve disease', 'urethral stricture',
       'vitamin d deficiency', 'hydatidiform mole',
       'pain disorder affecting the neck', 'tuberculosis',
       'pelvic fistula', 'acute bronchiolitis', 'presbyopia', 'dementia',
       'insect bite', 'paroxysmal ventricular tachycardia',
       'congenital heart defect', 'connective tissue disorder',
       'foreign body in the eye', 'poisoning due to gas',
       'pyogenic skin infection', 'endometrial hyperplasia',
       'acanthosis nigricans', 'central atherosclerosis',
       'viral exanthem', 'noninfectious gastroenteritis',
       'benign prostatic hyperplasia (bph)', 'menopause',
       'primary immunodeficiency', 'ovarian cancer', 'cataract',
       'dislocation of the hip', 'spinal stenosis',
       'intestinal obstruction', 'heart contusion',
       'congenital malformation syndrome', 'sporotrichosis',
       'lymphangitis', 'wernicke korsakoff syndrome',
       'intestinal disease', 'acute bronchitis',
       'persistent vomiting of unknown cause', 'open wound of the foot',
       'myocarditis', 'preeclampsia', 'ischemic heart disease',
       'neurofibromatosis', 'chickenpox', 'pancreatic cancer',
       'neuropathy due to drugs', 'croup',
       'idiopathic excessive menstruation', 'amblyopia',
       'meckel diverticulum', 'dislocation of the wrist',
       'ear drum damage', 'erectile dysfunction',
       'temporary or benign blood in urine',
       'kidney disease due to longstanding hypertension',
       'chondromalacia of the patella', 'onychomycosis',
       'urethral disorder', 'lyme disease', 'iron deficiency anemia',
       'acute respiratory distress syndrome (ards)',
       'toxic multinodular goiter', 'open wound of the finger',
       'autonomic nervous system disorder', 'psychosexual disorder',
       'anemia', 'tendinitis', 'common cold',
       'amyotrophic lateral sclerosis (als)',
       'central retinal artery or vein occlusion',
       'paroxysmal supraventricular tachycardia', 'venous insufficiency',
       'trichomonas infection', 'acne', 'depression', 'drug abuse',
       'urinary tract obstruction', 'diabetes insipidus', 'iridocyclitis',
       'varicocele of the testicles', 'irritable bowel syndrome',
       'fracture of the foot', 'ovarian cyst', 'chlamydia',
       'parasitic disease', 'fracture of the jaw', 'lipoma',
       'female genitalia infection', 'pulmonary hypertension',
       'thyroid nodule', 'broken tooth', 'dumping syndrome',
       'lymphadenitis', 'injury to the face', 'aortic valve disease',
       'rheumatoid arthritis', 'spermatocele', 'impetigo', 'anal fistula',
       'hypothermia', 'oppositional disorder', 'migraine',
       'diabetic peripheral neuropathy', 'testicular disorder',
       'gestational diabetes', 'hidradenitis suppurativa', 'valley fever',
       'conjunctivitis due to bacteria', 'lewy body dementia',
       'multiple myeloma', 'head injury', 'ascending cholangitis',
       'idiopathic irregular menstrual cycle',
       'interstitial lung disease', 'mononeuritis', 'malaria',
       'somatization disorder', 'hypovolemia', 'schizophrenia',
       'knee ligament or meniscus tear', 'endocarditis', 'sepsis',
       'heat stroke', 'cholecystitis', 'cardiac arrest', 'cardiomyopathy',
       'social phobia', 'meningitis', 'spherocytosis', 'hormone disorder',
       'raynaud disease', 'reactive arthritis', 'scabies',
       'ear wax impaction', 'hypertension of pregnancy',
       'peripheral arterial embolism', 'rosacea', 'fracture of the skull',
       'uveitis', 'fracture of the facial bones', 'tracheitis',
       'jaw disorder', 'perirectal infection', 'breast cyst',
       'post-traumatic stress disorder (ptsd)', 'kidney cancer',
       'vulvar cancer', 'blepharitis', 'celiac disease', 'cystitis',
       'sickle cell anemia', 'subconjunctival hemorrhage', 'hemorrhoids',
       'contact dermatitis', 'sinus bradycardia', 'high blood pressure',
       'pelvic inflammatory disease', 'liver disease',
       'chronic constipation', 'thyroid cancer', 'flu',
       'friedrich ataxia', 'tic (movement) disorder', 'skin polyp',
       'brachial neuritis', 'cervical cancer', 'adrenal adenoma',
       'esophagitis', 'gas gangrene', 'yeast infection', 'spina bifida',
       'drug poisoning due to medication', 'alcoholic liver disease',
       'malignant hypertension', 'diverticulitis', 'moyamoya disease',
       'heat exhaustion', 'psychotic disorder', 'frostbite',
       'atrophy of the corpus cavernosum', 'smoking or tobacco addiction',
       'sprain or strain', 'essential tremor', 'open wound of the ear',
       'foreign body in the nose', 'idiopathic painful menstruation',
       'down syndrome', 'idiopathic infrequent menstruation',
       'pneumothorax', 'de quervain disease', 'fracture of the vertebra',
       'human immunodeficiency virus infection (hiv)', 'mumps',
       'subarachnoid hemorrhage', 'acute fatty liver of pregnancy (aflp)',
       'ectropion', 'scar', 'lactose intolerance',
       'eustachian tube dysfunction (ear disorder)', 'appendicitis',
       'graves disease', 'dissociative disorder',
       'open wound of the face', 'dislocation of the vertebra',
       'phimosis', 'hyperemesis gravidarum', 'pregnancy', 'thalassemia',
       'placenta previa', 'epidural hemorrhage', 'septic arthritis',
       "athlete's foot", 'pleural effusion', 'aphakia', 'vulvar disorder',
       'sialoadenitis', 'gynecomastia', 'urinary tract infection',
       'histoplasmosis', 'erythema multiforme', 'scoliosis', 'bunion',
       'arrhythmia', 'trigeminal neuralgia', 'ankylosing spondylitis',
       'peripheral nerve disorder', 'sebaceous cyst',
       'poisoning due to antipsychotics', 'neurosis', 'prostate cancer',
       'cerebral edema', 'dislocation of the finger', 'birth trauma',
       'chronic pancreatitis', 'hematoma', 'carcinoid syndrome',
       'open wound of the head', 'seborrheic keratosis', 'burn',
       'spontaneous abortion', 'genital herpes', 'adjustment reaction',
       'gallstone', 'multiple sclerosis', 'zenker diverticulum',
       'fracture of the pelvis', 'pneumoconiosis', 'hyperlipidemia',
       'ulcerative colitis', 'male genitalia infection', 'hpv', 'angina',
       'injury to the spinal cord', 'nasal polyp', 'lichen simplex',
       'trichiasis', 'acariasis', 'colorectal cancer',
       'skin pigmentation disorder', 'factitious disorder',
       'lymphogranuloma venereum', 'galactorrhea of unknown cause',
       'g6pd enzyme deficiency', 'nerve impingement near the shoulder',
       'toxoplasmosis', 'fibroadenoma', 'open wound of the hand',
       'missed abortion', 'diabetic ketoacidosis', 'granuloma inguinale',
       'obsessive compulsive disorder (ocd)', 'injury of the ankle',
       'hyponatremia', 'stricture of the esophagus',
       'fracture of the ankle', 'soft tissue sarcoma', 'bone disorder',
       'epilepsy', 'personality disorder', 'shingles (herpes zoster)',
       'tourette syndrome', 'avascular necrosis', 'strep throat',
       'spinocerebellar ataxia', 'osteomyelitis', 'sjogren syndrome',
       'adhesive capsulitis of the shoulder', 'viral hepatitis',
       'tonsillar hypertrophy', 'gastritis', 'skin cancer',
       'rheumatic fever', 'aphthous ulcer', 'tonsillitis',
       'intestinal cancer', 'rocky mountain spotted fever',
       'stomach cancer', 'developmental disability',
       'acute stress reaction', 'delirium', 'callus',
       'guillain barre syndrome', 'lumbago', 'deviated nasal septum',
       'hemangioma', 'peripheral arterial disease', 'chronic back pain',
       'heart failure', 'conjunctivitis', 'herniated disk',
       'rhabdomyolysis', 'breast infection (mastitis)',
       'abdominal aortic aneurysm', 'pulmonary embolism',
       'conduct disorder', 'mastectomy', 'epididymitis',
       'premature rupture of amniotic membrane', 'molluscum contagiosum',
       'necrotizing fasciitis', 'benign vaginal discharge (leukorrhea)',
       'bladder obstruction', 'melanoma', 'cervical disorder',
       'laryngitis', 'dyshidrosis', 'poisoning due to opioids',
       'diaper rash', 'lichen planus', 'gastroduodenal ulcer',
       'inguinal hernia', 'eczema', 'asperger syndrome', 'mucositis',
       'paronychia', 'open wound of the jaw', 'white blood cell disease',
       'kaposi sarcoma', 'spondylolisthesis', 'pseudotumor cerebri',
       'conjunctivitis due to virus', 'open wound of the nose'],
      dtype=object)

In [9]:
df['diseases'].value_counts()

diseases
cystitis                          1219
nose disorder                     1218
vulvodynia                        1218
complex regional pain syndrome    1217
spondylosis                       1216
                                  ...
open wound of the head               1
myocarditis                          1
chronic ulcer                        1
hypergammaglobulinemia               1
kaposi sarcoma                       1
Name: count, Length: 773, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['disease_encoded'] = le.fit_transform(df['diseases'])

In [11]:
df[['diseases','disease_encoded']].head()

         diseases  disease_encoded
0  panic disorder              531
1  panic disorder              531
2  panic disorder              531
3  panic disorder              531
4  panic disorder              531

In [12]:
X = df.drop(['diseases','disease_encoded'], axis=1)
y = df['disease_encoded']

In [13]:
X.head()

,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,palpitations,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,1,0,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,1,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [18]:
model.score(X_test, y_test)

0.8644839944117111

In [19]:
sample = X_test.iloc[:1]
sample

,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,palpitations,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
94355,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
prediction = model.predict(sample)
prediction

array([621])

In [21]:
le.inverse_transform(prediction)

array(['retinal detachment'], dtype=object)

In [22]:
y_test.iloc[:1]

94355    121
Name: disease_encoded, dtype: int64

In [23]:
le.inverse_transform(y_test.iloc[:1])

array(['chronic glaucoma'], dtype=object)

In [24]:
predictions = model.predict(X_test.iloc[:10])
le.inverse_transform(predictions)

array(['retinal detachment', 'torticollis', 'schizophrenia',
       'fracture of the patella', 'chronic otitis media', 'arrhythmia',
       'chronic otitis media', 'multiple sclerosis', 'neuralgia',
       'hyperkalemia'], dtype=object)

In [25]:
le.inverse_transform(y_test.iloc[:10])

array(['chronic glaucoma', 'torticollis', 'personality disorder',
       'fracture of the patella', 'chronic otitis media', 'arrhythmia',
       'chronic otitis media', 'peripheral nerve disorder', 'neuralgia',
       'hyperkalemia'], dtype=object)

In [26]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      1.00      0.83        20
           1       0.95      0.94      0.94        81
           2       0.60      0.91      0.73        58
           3       1.00      1.00      1.00         6
           4       0.95      0.94      0.94        63
           5       0.75      1.00      0.86         6
           6       0.42      1.00      0.59         5
           7       0.65      1.00      0.78        20
           8       0.60      0.91      0.73       103
           9       0.93      0.78      0.85       179
          10       1.00      0.89      0.94       253
          11       0.98      0.63      0.77       221
          12       0.74      0.78      0.76       187
          13       0.43      1.00      0.60         3
          14       0.45      0.55      0.49        31
          15       1.00      0.96      0.98       209
          16       0.72      0.93      0.81       145
          17       1.00      0.84      0.91       246
          18       0.83      0.95      0.89        82
          19       0.90      0.82      0.86       179
          20       0.95      0.90      0.93       185
          21       0.85      1.00      0.92        17
          22       0.73      0.90      0.80        89
          23       1.00      0.89      0.94         9
          24       0.50      1.00      0.67         1
          25       0.77      0.94      0.85        87
          26       0.94      1.00      0.97        62
          27       0.99      0.95      0.97       148
          28       1.00      0.93      0.96        44
          29       0.99      0.87      0.92       182
          30       0.67      1.00      0.80         8
          31       0.72      0.97      0.83        70
          32       0.93      0.96      0.94        70
          33       0.87      1.00      0.93        13
          34       1.00      1.00      1.00         1
          35       0.90      1.00      0.95         9
          36       0.76      0.97      0.85        36
          37       0.33      1.00      0.50         1
          38       0.93      0.98      0.96        57
          39       1.00      0.83      0.91         6
          40       1.00      1.00      1.00         1
          41       1.00      0.86      0.92         7
          42       0.99      0.91      0.95       179
          43       0.85      0.94      0.89       126
          44       1.00      0.91      0.95       236
          45       0.97      0.92      0.94        84
          46       0.12      1.00      0.22         1
          47       0.74      0.98      0.84        44
          48       1.00      1.00      1.00        16
          49       0.85      0.85      0.85       183
          50       0.91      0.75      0.82        52
          51       1.00      0.96      0.98       228
          52       0.77      1.00      0.87        10
          53       0.75      1.00      0.86        80
          54       1.00      1.00      1.00         3
          55       0.76      0.78      0.77       189
          56       0.58      0.80      0.67        55
          57       0.60      0.95      0.74        22
          58       0.68      0.89      0.77        73
          59       0.71      1.00      0.83        15
          60       0.60      0.63      0.62        19
          61       0.88      0.90      0.89        51
          62       0.61      0.88      0.72        85
          63       0.81      0.94      0.87        66
          64       0.62      1.00      0.77         5
          65       0.75      0.90      0.82        99
          66       0.92      0.95      0.93        73
          67       0.91      0.95      0.93        21
          68       1.00      0.50      0.67         8
          69       0.99      0.99      0.99       106
          70       0.99      0.94      0.97       140
          71       0.78      0.98      0.87        48
          72       0.93      0.95      0.94        82
          73       1.00      0.91      0.95       244
          74       0.94      0.89      0.92       131
          75       0.61      0.61      0.61       132
          76       1.00      1.00      1.00         1
          77       0.96      1.00      0.98        27
          78       0.46      0.84      0.59        83
          79       0.93      0.95      0.94        66
          80       0.84      0.72      0.78       180
          81       0.50      1.00      0.67         1
          82       1.00      0.96      0.98        23
          83       0.96      1.00      0.98        51
          84       0.56      1.00      0.71         5
          85       0.94      0.90      0.92       177
          86       0.80      0.96      0.87        45
          87       0.00      0.00      0.00         0
          88       0.75      0.60      0.67         5
          89       0.99      1.00      0.99        96
          90       0.92      1.00      0.96        33
          91       1.00      0.78      0.88         9
          92       0.53      0.90      0.67        10
          93       1.00      0.98      0.99       252
          94       0.93      0.71      0.81        97
          95       0.76      0.84      0.80        19
          96       0.00      0.00      0.00         2
          97       0.95      0.96      0.95        72
          98       0.77      0.96      0.85        52
          99       0.96      0.95      0.95       167
         100       1.00      1.00      1.00         2
         101       0.85      0.60      0.70       115
         102       0.58      0.97      0.73        29
         103       1.00      0.97      0.98        33
         104       0.57      1.00      0.73         4
         105       0.75      0.86      0.80        14
         106       0.68      1.00      0.81        21
         107       0.95      0.95      0.95        21
         108       0.95      0.95      0.95        21
         109       0.69      1.00      0.82         9
         110       0.73      0.95      0.82        76
         111       0.88      0.87      0.87       112
         112       0.91      0.91      0.91        23
         113       0.52      0.80      0.63        30
         114       1.00      0.74      0.85       275
         115       0.84      0.98      0.90        85
         116       0.88      1.00      0.93         7
         117       0.56      0.83      0.67         6
         118       0.56      0.93      0.70        15
         119       0.99      0.93      0.96       187
         120       0.98      0.81      0.89       178
         121       0.80      0.71      0.75       146
         122       0.50      1.00      0.67         2
         123       1.00      1.00      1.00         2
         124       0.55      0.91      0.68        33
         125       0.60      0.81      0.69       168
         126       0.85      0.90      0.87       136
         127       0.82      0.90      0.86       127
         128       0.98      0.98      0.98        55
         129       0.70      0.91      0.79        35
         130       0.75      0.93      0.83       137
         132       1.00      1.00      1.00        56
         133       1.00      1.00      1.00        16
         134       0.90      1.00      0.95        36
         135       0.81      0.98      0.89        60
         136       0.25      1.00      0.40         2
         137       0.85      0.90      0.87       148
         138       0.95      0.87      0.91       244
         139       1.00      0.95      0.98       239
         140       0.95      0.90      0.92       134
         141       0.90      0.92      0.91       103
         142       0.80      1.00      0.89         8
         143       1.00      1.00      1.00         2
         144       1.00      0.82      0.90       197
         145       1.00      0.86      0.92       242
         146       0.63      0.97      0.77        32
         147       0.73      0.87      0.79       131
         149       0.85      0.85      0.85       192
         150       0.40      1.00      0.57         2
         151       0.99      0.71      0.83       186
         152       0.57      0.80      0.67       104
         153       0.60      0.59      0.60       122
         154       0.85      0.77      0.81        22
         155       0.93      0.96      0.94        67
         156       0.96      0.64      0.77        75
         157       0.90      0.84      0.87       202
         158       0.91      0.91      0.91        11
         159       1.00      1.00      1.00         5
         161       1.00      1.00      1.00         2
         162       0.67      1.00      0.80         4
         163       0.80      1.00      0.89         4
         164       1.00      0.89      0.94         9
         165       0.95      0.70      0.81       266
         166       0.73      0.92      0.81        12
         168       0.95      1.00      0.98        40
         169       0.66      0.81      0.73       182
         170       0.98      0.87      0.92       136
         171       0.85      0.90      0.87        69
         172       1.00      1.00      1.00         1
         173       1.00      0.88      0.93       236
         174       1.00      0.60      0.75       198
         175       0.65      0.83      0.73        88
         176       0.99      0.91      0.95       188
         177       0.93      0.98      0.96       126
         178       0.00      0.00      0.00         1
         179       0.00      0.00      0.00         0
         180       0.95      0.95      0.95       119
         182       0.98      0.98      0.98        83
         183       0.52      0.72      0.60        88
         184       0.99      0.97      0.98       200
         185       0.80      1.00      0.89         4
         186       0.90      1.00      0.95        19
         187       0.43      1.00      0.60         3
         188       1.00      1.00      1.00         3
         189       1.00      1.00      1.00         4
         191       0.00      0.00      0.00         0
         192       0.69      1.00      0.82         9
         193       0.65      1.00      0.79        13
         194       0.73      1.00      0.84         8
         195       0.96      1.00      0.98        24
         196       0.96      0.78      0.87       246
         197       0.87      0.89      0.88       143
         198       0.89      1.00      0.94        39
         199       0.94      0.89      0.91       124
         200       0.45      0.87      0.59        15
         201       0.52      0.91      0.66        57
         202       0.87      0.88      0.87        74
         203       0.75      0.77      0.76       114
         204       1.00      0.95      0.98        43
         205       0.99      0.96      0.97       176
         206       0.96      0.92      0.94        53
         207       1.00      0.40      0.57       174
         208       0.00      0.00      0.00         0
         209       0.49      1.00      0.65        17
         210       0.94      0.93      0.93        97
         211       0.98      0.82      0.89       192
         212       0.74      0.95      0.83       133
         213       0.92      1.00      0.96        83
         214       0.73      0.92      0.82        65
         215       0.30      1.00      0.46         8
         216       0.99      0.66      0.79       227
         217       1.00      1.00      1.00         1
         218       0.58      0.88      0.70         8
         219       0.40      1.00      0.57         2
         220       0.83      0.95      0.88        20
         221       0.38      0.95      0.54        19
         222       0.88      1.00      0.94        22
         223       1.00      1.00      1.00         8
         224       0.92      0.94      0.93        64
         225       0.31      1.00      0.48        10
         226       0.95      0.99      0.97       106
         227       1.00      1.00      1.00         4
         228       1.00      0.95      0.97        95
         229       0.00      0.00      0.00         0
         230       0.80      0.92      0.86        13
         231       0.91      0.86      0.88       126
         232       0.82      1.00      0.90         9
         233       1.00      0.89      0.94        19
         234       0.00      0.00      0.00         3
         235       1.00      0.90      0.94       263
         236       0.87      0.94      0.90        35
         237       0.99      0.92      0.96       169
         238       0.92      1.00      0.96        12
         239       0.99      0.94      0.97        88
         240       0.50      1.00      0.67         1
         241       1.00      0.97      0.99        36
         242       1.00      1.00      1.00         6
         243       0.00      0.00      0.00         0
         244       1.00      0.92      0.96        24
         245       1.00      1.00      1.00         2
         246       0.73      0.76      0.75       127
         247       0.64      1.00      0.78         7
         248       0.19      0.83      0.30         6
         249       0.91      0.90      0.90       116
         250       0.90      0.91      0.91        69
         251       0.47      1.00      0.64         7
         252       0.91      0.99      0.95        95
         253       0.60      1.00      0.75         6
         254       0.41      0.84      0.55        57
         255       0.92      1.00      0.96        22
         257       0.90      1.00      0.95        35
         258       0.80      1.00      0.89         4
         259       0.82      0.82      0.82        11
         260       0.92      0.90      0.91        81
         261       1.00      0.93      0.96        96
         262       0.14      1.00      0.25         1
         263       0.60      1.00      0.75         3
         264       0.71      0.68      0.70        22
         265       0.71      1.00      0.83        12
         266       0.97      0.93      0.95       148
         267       0.59      1.00      0.74        10
         268       0.95      0.95      0.95        20
         269       0.78      0.98      0.87        43
         270       0.99      0.95      0.97       172
         271       0.88      1.00      0.93        35
         272       0.73      0.89      0.80         9
         273       0.91      0.98      0.94        50
         275       1.00      1.00      1.00         4
         276       1.00      0.68      0.81       279
         277       0.61      0.77      0.68       126
         278       0.50      1.00      0.67         1
         279       1.00      0.67      0.80         3
         280       0.65      0.91      0.76       176
         281       0.99      0.97      0.98       158
         283       0.85      0.82      0.83       141
         284       0.90      0.88      0.89       139
         285       0.96      0.92      0.94        76
         286       1.00      0.92      0.96       239
         287       0.49      0.92      0.64        37
         288       0.80      1.00      0.89        45
         289       0.60      1.00      0.75         6
         290       0.83      0.71      0.76        96
         291       0.50      1.00      0.67         2
         292       1.00      1.00      1.00        17
         293       0.94      1.00      0.97        17
         294       0.98      0.91      0.94       252
         295       0.67      1.00      0.80         2
         296       0.96      0.96      0.96        49
         297       0.81      1.00      0.89        17
         298       1.00      0.71      0.83       197
         299       0.94      0.94      0.94        18
         300       0.00      0.00      0.00         0
         301       1.00      1.00      1.00         1
         302       1.00      0.97      0.99        75
         303       0.81      0.97      0.89        36
         304       0.94      0.97      0.95        30
         305       0.99      0.94      0.96       167
         306       0.88      0.90      0.89       110
         307       0.00      0.00      0.00         3
         308       0.98      0.90      0.94       176
         309       0.85      0.85      0.85        47
         311       0.85      0.78      0.82       130
         312       1.00      1.00      1.00         3
         313       0.89      0.89      0.89         9
         314       0.93      0.94      0.94       120
         315       1.00      1.00      1.00         1
         316       0.50      1.00      0.67         1
         317       0.86      1.00      0.92         6
         318       0.97      0.85      0.91       202
         319       0.69      1.00      0.81        11
         320       0.92      0.96      0.94        69
         321       0.80      0.78      0.79       174
         322       0.92      0.93      0.93        91
         323       1.00      0.91      0.95       185
         324       0.83      1.00      0.91        35
         325       0.00      0.00      0.00         0
         326       0.75      0.50      0.60         6
         327       0.86      1.00      0.92         6
         328       1.00      1.00      1.00         1
         329       1.00      1.00      1.00         7
         330       0.50      1.00      0.67         2
         332       0.00      0.00      0.00         1
         333       0.82      1.00      0.90        14
         334       0.76      0.97      0.85        39
         335       0.81      0.93      0.87        28
         336       0.74      0.96      0.84        70
         337       0.33      1.00      0.50         1
         339       0.96      0.90      0.93       160
         340       0.00      0.00      0.00         1
         341       0.56      1.00      0.71         5
         342       0.94      0.95      0.95       123
         343       1.00      1.00      1.00         1
         344       0.65      0.92      0.76        12
         345       0.83      1.00      0.91        25
         346       1.00      1.00      1.00         1
         347       0.83      1.00      0.91        10
         348       0.98      0.97      0.97       183
         349       0.00      0.00      0.00         0
         350       1.00      0.86      0.92         7
         351       1.00      0.94      0.97       244
         352       0.96      0.86      0.91       101
         353       0.95      0.94      0.94        93
         354       0.50      1.00      0.67         2
         355       1.00      0.94      0.97        17
         356       0.85      0.98      0.91        83
         357       1.00      0.94      0.97       104
         358       0.87      0.80      0.83       173
         359       0.67      1.00      0.80        10
         360       0.89      0.79      0.84       192
         361       0.74      1.00      0.85        20
         362       0.91      0.80      0.85       184
         363       0.74      0.93      0.82        92
         364       0.99      0.87      0.92       149
         365       0.47      0.95      0.62        74
         366       0.78      0.90      0.84       100
         367       0.72      0.95      0.82        57
         368       0.67      1.00      0.80         6
         369       0.70      0.78      0.74       254
         370       0.99      0.89      0.94       111
         371       0.97      0.86      0.91        74
         372       0.93      0.93      0.93        40
         373       0.71      1.00      0.83        35
         374       0.80      0.92      0.86        13
         375       1.00      0.93      0.96       258
         376       1.00      0.94      0.97        81
         377       1.00      1.00      1.00         2
         378       0.79      0.82      0.81        28
         379       0.27      0.60      0.38         5
         380       0.73      1.00      0.84         8

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [28]:
model.predict_proba(X_test.iloc[:5])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB

scores = cross_val_score(GaussianNB(), X, y, cv=5)
scores

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

array([0.86393731, 0.8679868 , 0.86729839, 0.86735913, 0.86420053])

In [31]:
scores.mean()

np.float64(0.8661564315940797)

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB

clf = Pipeline([
    ('nb', GaussianNB())
])

In [33]:
clf.fit(X_train, y_train)

Pipeline(steps=[('nb', GaussianNB())])

In [34]:
clf.score(X_test, y_test)

0.8644839944117111

In [35]:
pred = clf.predict(X_test.iloc[:5])
le.inverse_transform(pred)

array(['retinal detachment', 'torticollis', 'schizophrenia',
       'fracture of the patella', 'chronic otitis media'], dtype=object)

In [37]:
df.isnull().sum()

diseases                            0
anxiety and nervousness             0
depression                          0
shortness of breath                 0
depressive or psychotic symptoms    0
                                   ..
back swelling                       0
ankle stiffness or tightness        0
ankle weakness                      0
neck weakness                       0
disease_encoded                     0
Length: 379, dtype: int64

In [38]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import GaussianNB

clf = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('nb', GaussianNB())
])

In [39]:
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8644839944117111

In [40]:
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
cm

array([[ 20,   0,   0, ...,   0,   0,   0],
       [  0,  76,   0, ...,   0,   0,   0],
       [  0,   0,  53, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   1,   0,   0],
       [  0,   0,   0, ...,   0, 102,   0],
       [  0,   0,   0, ...,   0,   0,   2]])