### Machine Learning Tutorial - Naive Bayes: Exercise

Use wine dataset from sklearn.datasets to classify wines into 3 categories. Load the dataset and split it into test and train. After that train the model using Gaussian and Multinominal classifier and post which model performs better. Use the trained model to perform some predictions on test data.

In [ ]:
import pandas as pd
from sklearn.datasets import load_wine

In [ ]:
wine = load_wine()

In [ ]:
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [ ]:
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [ ]:
df['target'] = wine.target
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [ ]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [ ]:
X = df.drop('target', axis=1)
y = df.target

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.naive_bayes import GaussianNB

g_model = GaussianNB()
g_model.fit(X_train, y_train)

GaussianNB()

In [ ]:
g_model.score(X_test, y_test)

1.0

In [ ]:
g_model.predict(X_test[:5])

array([0, 0, 2, 0, 1])

In [ ]:
y_test[:5]

19     0
45     0
140    2
30     0
67     1
Name: target, dtype: int64

In [ ]:
from sklearn.naive_bayes import MultinomialNB

m_model = MultinomialNB()
m_model.fit(X_train, y_train)

MultinomialNB()

In [ ]:
m_model.score(X_test, y_test)

0.8888888888888888

In [ ]:
print("Gaussian Accuracy:", g_model.score(X_test, y_test))
print("Multinomial Accuracy:", m_model.score(X_test, y_test))

Gaussian Accuracy: 1.0
Multinomial Accuracy: 0.8888888888888888

In [ ]:
Gaussian Naive Bayes performed better with 100% accuracy compared to Multinomial Naive Bayes with 88.89% accuracy on the wine dataset. Therefore, GaussianNB is the better model for this dataset.