In [ ]:
AI-Based Healthcare Risk Assessment and Patient Outcome Prediction Using Regression Models

Problem statement:
This project focuses on developing a machine learning-based healthcare prediction system that analyzes patient information such as age, symptom count,severity score,
breathing difficulty, and chest pain indicators to estimate important healthcare outcomes including patient risk score,expected hospital waiting time,and recovery duration.
By applying Single Linear Regression, Multiple Linear Regression, and Multivariate Regression techniques,the project demonstrates how predictive analytics can assist in
healthcare decision-making, patient prioritization,and efficient hospital resource management through data-driven outcome prediction.

In [ ]:
Single Linear regression

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 500

age = np.random.randint(18, 80, n)
symptoms_count = np.random.randint(1, 8, n)
severity_score = np.random.randint(1, 11, n)
breathing_difficulty = np.random.randint(0, 2, n)
chest_pain = np.random.randint(0, 2, n)

risk_score = (
    age * 0.3 +
    symptoms_count * 8 +
    severity_score * 5 +
    breathing_difficulty * 15 +
    chest_pain * 20 +
    np.random.normal(0, 5, n)
)

df = pd.DataFrame({
    'Age': age,
    'Symptoms_Count': symptoms_count,
    'Severity_Score': severity_score,
    'Breathing_Difficulty': breathing_difficulty,
    'Chest_Pain': chest_pain,
    'Risk_Score': risk_score
})

df.head()

,Age,Symptoms_Count,Severity_Score,Breathing_Difficulty,Chest_Pain,Risk_Score
0,56,6,1,1,1,105.496713
1,69,7,1,1,0,98.962674
2,46,2,8,0,1,89.132101
3,32,7,2,0,0,81.029332
4,60,3,8,0,1,91.495406

In [2]:
df.to_csv("healthcare_regression_dataset.csv", index=False)

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df[['Symptoms_Count']]
y = df['Risk_Score']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [5]:
print("Slope:", model.coef_[0])
print("Intercept:", model.intercept_)

Slope: 6.97395585032346
Intercept: 63.77008052665444

In [6]:
pred = model.predict(X_test)
pred[:10]

array([105.61381563, 112.58777148,  98.63985978,  77.71799223,
        77.71799223, 112.58777148,  98.63985978,  70.74403638,
        91.66590393,  70.74403638])

In [ ]:
Multiple linear regression

In [7]:
X = df[[
    'Age',
    'Symptoms_Count',
    'Severity_Score',
    'Breathing_Difficulty',
    'Chest_Pain'
]]

y = df['Risk_Score']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

multi_model = LinearRegression()
multi_model.fit(X_train, y_train)

LinearRegression()

In [8]:
print(multi_model.coef_)
print(multi_model.intercept_)

[ 0.29171201  7.99160216  5.0784415  15.00432061 19.49678942]
0.24839492396503715

In [9]:
from sklearn.metrics import r2_score

pred = multi_model.predict(X_test)

print(r2_score(y_test, pred))

0.958380324017755

In [ ]:
Multivariate linear regression

In [10]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 500

age = np.random.randint(18, 80, n)
symptoms_count = np.random.randint(1, 8, n)
severity_score = np.random.randint(1, 11, n)
breathing_difficulty = np.random.randint(0, 2, n)
chest_pain = np.random.randint(0, 2, n)

risk_score = (
    age*0.3 +
    symptoms_count*8 +
    severity_score*5 +
    breathing_difficulty*15 +
    chest_pain*20 +
    np.random.normal(0, 5, n)
)

wait_time = (
    severity_score*4 +
    symptoms_count*3 +
    breathing_difficulty*10 +
    np.random.normal(0, 3, n)
)

recovery_days = (
    severity_score*1.2 +
    symptoms_count*0.8 +
    age*0.05 +
    np.random.normal(0, 2, n)
)

df = pd.DataFrame({
    'Age': age,
    'Symptoms_Count': symptoms_count,
    'Severity_Score': severity_score,
    'Breathing_Difficulty': breathing_difficulty,
    'Chest_Pain': chest_pain,
    'Risk_Score': risk_score,
    'Wait_Time': wait_time,
    'Recovery_Days': recovery_days
})

df.head()

,Age,Symptoms_Count,Severity_Score,Breathing_Difficulty,Chest_Pain,Risk_Score,Wait_Time,Recovery_Days
0,56,6,1,1,1,105.496713,31.113376,11.896000
1,69,7,1,1,0,98.962674,35.456947,8.727185
2,46,2,8,0,1,89.132101,39.138446,13.884586
3,32,7,2,0,0,81.029332,34.434514,9.303554
4,60,3,8,0,1,91.495406,40.752057,13.243034

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df[[
    'Age',
    'Symptoms_Count',
    'Severity_Score',
    'Breathing_Difficulty',
    'Chest_Pain'
]]

Y = df[[
    'Risk_Score',
    'Wait_Time',
    'Recovery_Days'
]]

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [12]:
pred = model.predict(X_test)
pred[:5]

array([[110.18122482,  47.78659656,  14.08853542],
       [ 94.70885805,  41.06769607,  13.29625977],
       [ 76.44499502,  26.75538159,  10.66641124],
       [ 68.70510846,  26.25806409,   8.96498262],
       [ 70.8613078 ,  37.85563429,  13.51477996]])