In [4]:
import zipfile

In [6]:
with zipfile.ZipFile('/content/healthcare_dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/healthcare_data')

In [7]:
import os
os.listdir('/content/healthcare_data')

['Final_Augmented_dataset_Diseases_and_Symptoms.csv']

In [8]:
import pandas as pd

df = pd.read_csv('/content/healthcare_data/Final_Augmented_dataset_Diseases_and_Symptoms.csv')
df.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df.shape

(246945, 378)

In [10]:
df.isnull().sum().sum()

np.int64(0)

In [11]:
df['diseases'].nunique()

773

In [12]:
df['diseases'].value_counts().head(20)

diseases
cystitis                          1219
nose disorder                     1218
vulvodynia                        1218
complex regional pain syndrome    1217
spondylosis                       1216
vaginal cyst                      1215
esophagitis                       1215
peripheral nerve disorder         1215
hypoglycemia                      1215
conjunctivitis due to allergy     1215
gastrointestinal hemorrhage       1214
diverticulitis                    1214
acute bronchitis                  1213
infectious gastroenteritis        1212
fungal infection of the hair      1212
sprain or strain                  1212
pneumonia                         1212
spontaneous abortion              1212
gout                              1211
marijuana abuse                   1210
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['disease_encoded'] = le.fit_transform(df['diseases'])

df[['diseases', 'disease_encoded']].head()

         diseases  disease_encoded
0  panic disorder              531
1  panic disorder              531
2  panic disorder              531
3  panic disorder              531
4  panic disorder              531

In [14]:
X = df.drop(['diseases', 'disease_encoded'], axis=1)
y = df['disease_encoded']

X.shape, y.shape

((246945, 377), (246945,))

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

X_train.shape, X_test.shape

((197556, 377), (49389, 377))

In [16]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train, y_train)

LinearSVC(random_state=42)

In [19]:
svm_model.score(X_test, y_test)

0.8612646540727692